# Generated by Django 2.2.4 on 2020-06-03 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
                ('order_date', models.DateField(default=datetime.datetime.today)),
                ('delivery_date', models.DateField(default=datetime.datetime(2020, 6, 8, 12, 41, 33, 616355))),
            ],
        ),
    ]
