# Generated by Django 2.2.4 on 2020-06-03 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_billingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingmodel',
            name='address',
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 8, 12, 43, 36, 394349)),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='payment_mode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
