# Generated by Django 2.2.4 on 2020-06-03 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200603_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmodel',
            name='address',
            field=models.TextField(default='Enter your adress here..'),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 8, 12, 45, 0, 156220)),
        ),
    ]
