# Generated by Django 2.2.4 on 2020-06-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200603_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingmodel',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='billingmodel',
            name='delivery_time',
            field=models.CharField(default='16:42:02', max_length=20),
        ),
        migrations.AddField(
            model_name='billingmodel',
            name='order_time',
            field=models.CharField(default='14:42:02', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='order_date',
            field=models.CharField(default='06/03/20', max_length=50),
        ),
    ]
