# Generated by Django 2.2.4 on 2020-06-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200603_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='address',
            field=models.TextField(default='Enter your address here..'),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='delivery_time',
            field=models.CharField(default='12:08:03', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='order_date',
            field=models.CharField(default='06/09/20', max_length=50),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='order_time',
            field=models.CharField(default='10:08:03', max_length=20),
        ),
    ]
