# Generated by Django 2.2.4 on 2020-06-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200609_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='delivery_time',
            field=models.CharField(default='12:16:26', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='order_time',
            field=models.CharField(default='10:16:26', max_length=20),
        ),
    ]
