# Generated by Django 2.2.4 on 2020-06-10 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_auto_20200609_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='delivery_time',
            field=models.CharField(default='06:16:18', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='order_date',
            field=models.CharField(default='06/10/20', max_length=50),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='order_time',
            field=models.CharField(default='04:16:18', max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.CharField(default='06/10/20', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
