# Generated by Django 2.2.4 on 2020-06-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200610_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmodel',
            name='cart_items',
            field=models.TextField(default='Yummy dishes here!'),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='delivery_time',
            field=models.CharField(default='11:30:52', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='order_time',
            field=models.CharField(default='09:30:52', max_length=20),
        ),
    ]
