# Generated by Django 2.2.4 on 2020-06-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200610_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmodel',
            name='discount_applied',
            field=models.CharField(default='500', max_length=10),
        ),
        migrations.AddField(
            model_name='billingmodel',
            name='item_disc',
            field=models.CharField(default='Discount applied', max_length=500),
        ),
        migrations.AddField(
            model_name='billingmodel',
            name='item_price',
            field=models.CharField(default='Item price', max_length=500),
        ),
        migrations.AddField(
            model_name='billingmodel',
            name='item_quantity',
            field=models.CharField(default='Item quantity', max_length=500),
        ),
        migrations.AddField(
            model_name='billingmodel',
            name='total_price',
            field=models.CharField(default='1000', max_length=10),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='delivery_time',
            field=models.CharField(default='11:58:24', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='order_time',
            field=models.CharField(default='09:58:24', max_length=20),
        ),
    ]
